/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.LivroControl;
import controler.ValidacaoException;
import javax.swing.JOptionPane;
import vo.LivrosVO;

/**
 *
 * @author leonardo
 */
public class Livros extends javax.swing.JFrame {

    /**
     * Creates new form Livros
     */
    public Livros() {
        initComponents();
    }
     private Principal buscaLivroPrincipal; //tabela
    
    public Livros(Principal buscaLivroPrincipal) {
        initComponents();
        this.setTitle("Cadastro Livro");
        this.bLivrosConfirmarEdicao.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.buscaLivroPrincipal = buscaLivroPrincipal;
        this.bLivrosEditar.setEnabled(false);
        
    }
    
    public Livros(Principal buscaLivroPrincipal, LivrosVO livroVO){
        initComponents();
        this.setTitle("Edição de Registro de Livro");
        this.bLivrosCadastrar.setEnabled(false);
        this.txtLivrosISBN.setEnabled(false);
        this.bLivrosConfirmarEdicao.setEnabled(false);
        
        this.setLocationRelativeTo(null);
        this.buscaLivroPrincipal= buscaLivroPrincipal;
        this.txtLivrosTitulo.setEnabled(false);
        this.txtLivrosAutor.setEnabled(false);
        this.txtLivrosQuantidade.setEnabled(false);
        this.cbLivroEditora.setEnabled(false);
        this.cbLivrosLocalDeEdicao.setEnabled(false);
       
        popularCampos(livroVO);
    }
    
    public void popularCampos(LivrosVO livroVO){
        this.getTISBN().setText(String.valueOf(livroVO.getISBN()));
        this.getTTitulo().setText(livroVO.getTitulo());
        this.getCbEditora().setSelectedItem(livroVO.getEditora());
        this.getTQuantidade().setText(String.valueOf(livroVO.getQuantidade()));
        this.getTAutor().setText(livroVO.getAutor() );
        this.cbLivrosLocalDeEdicao.setSelectedItem(livroVO.getLocalEdicao());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLivrosISBN = new javax.swing.JTextField();
        txtLivrosTitulo = new javax.swing.JTextField();
        txtLivrosAutor = new javax.swing.JTextField();
        txtLivrosQuantidade = new javax.swing.JTextField();
        cbLivrosLocalDeEdicao = new javax.swing.JComboBox<>();
        cbLivroEditora = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        bLivrosEditar = new javax.swing.JToggleButton();
        bLivrosConfirmarEdicao = new javax.swing.JToggleButton();
        bLivrosCadastrar = new javax.swing.JToggleButton();
        bLivrosCancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo:");

        jLabel2.setText("Autor:");

        jLabel3.setText("ISBN:");

        jLabel4.setText("Quantidade:");

        jLabel5.setText("Local de edição:");

        jLabel6.setText("Editora:");

        cbLivrosLocalDeEdicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Adamantina", "Apucarana", "Bauru", "Campinas", "Cascavel", "Curitiba", "Maringa", "Ponta Grossa", "Ribeirao Preto", "São Paulo", "Adamantina", "Apucarana", "Bauru", "Campinas", "Cascavel", "Curitiba", "Maringa", "Ponta Grossa", "Ribeirao Preto", "São Paulo 2", "Item 3", "Item 4" }));

        cbLivroEditora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Grupo Planeta", "Rocco", "Mundial", "LT", "CRV", "Natugraf", "CEO", "Livraria Garnier", "Typ" }));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel7.setText("*Todos os campos são obrigatórios.");

        bLivrosEditar.setText("Editar");
        bLivrosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivrosEditarActionPerformed(evt);
            }
        });

        bLivrosConfirmarEdicao.setText("Confirmar Edição");
        bLivrosConfirmarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivrosConfirmarEdicaoActionPerformed(evt);
            }
        });

        bLivrosCadastrar.setText("Cadastrar");
        bLivrosCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivrosCadastrarActionPerformed(evt);
            }
        });

        bLivrosCancelar.setText("Cancelar");
        bLivrosCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivrosCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtLivrosQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLivrosAutor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbLivrosLocalDeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbLivroEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtLivrosTitulo))
                                .addGap(91, 91, 91))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLivrosISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bLivrosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(bLivrosConfirmarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(bLivrosCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bLivrosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtLivrosISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLivrosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLivrosQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtLivrosAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbLivrosLocalDeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbLivroEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLivrosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLivrosConfirmarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLivrosCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLivrosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLivrosCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivrosCadastrarActionPerformed
         try {
            
             LivroControl livroControl = new LivroControl();
             livroControl.cadastrar(this.txtLivrosISBN.getText(),this.txtLivrosTitulo.getText(),this.cbLivroEditora.getSelectedItem().toString(),
                     this.txtLivrosQuantidade.getText(),this.txtLivrosAutor.getText(),this.cbLivrosLocalDeEdicao.getSelectedItem().toString());
            
             this.buscaLivroPrincipal.buscarLivros();
            
            JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!", "Cadastro Livro", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
        } catch (ValidacaoException validacaoException) {
            
            JOptionPane.showMessageDialog(rootPane, validacaoException.getMessage(), "Cadastro Livro", JOptionPane.WARNING_MESSAGE);
        
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao efetuar o cadastro!", "Cadastro Livro", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_bLivrosCadastrarActionPerformed

    private void bLivrosConfirmarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivrosConfirmarEdicaoActionPerformed
        try {
            LivroControl livroControl = new LivroControl();
            livroControl.editar(this.txtLivrosISBN.getText(),this.txtLivrosTitulo.getText(),this.cbLivroEditora.getSelectedItem().toString(),
                     this.txtLivrosQuantidade.getText(),this.txtLivrosAutor.getText(),this.cbLivrosLocalDeEdicao.getSelectedItem().toString());
            
            this.buscaLivroPrincipal.buscarLivros();
            
            JOptionPane.showMessageDialog(rootPane, "Edição realizada com sucesso!", "Editar Livro", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
        } catch (ValidacaoException validacaoException) {
            
            JOptionPane.showMessageDialog(rootPane, validacaoException.getMessage(), "Editar Livro", JOptionPane.WARNING_MESSAGE);
        
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao efetuar a edição!", "Editar Livro", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_bLivrosConfirmarEdicaoActionPerformed

    private void bLivrosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivrosEditarActionPerformed
        this.txtLivrosISBN.setEnabled(false);
        this.txtLivrosTitulo.setEnabled(true);
        this.txtLivrosQuantidade.setEnabled(true);
        this.txtLivrosAutor.setEnabled(true);
        this.cbLivrosLocalDeEdicao.setEnabled(true);
        this.cbLivroEditora.setEnabled(true);
        this.bLivrosConfirmarEdicao.setEnabled(true);
        this.bLivrosEditar.setEnabled(false);
        this.bLivrosCadastrar.setEnabled(false);
    }//GEN-LAST:event_bLivrosEditarActionPerformed

    private void bLivrosCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivrosCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bLivrosCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
 
    public javax.swing.JTextField getTISBN(){
        return txtLivrosISBN;
    }
    public javax.swing.JTextField getTTitulo(){
        return txtLivrosTitulo;
    }
    public javax.swing.JTextField getTAutor(){
        return txtLivrosAutor;
    }
    public javax.swing.JTextField getTQuantidade(){
        return txtLivrosQuantidade;
    }
    public javax.swing.JComboBox<String> getCbLocalEdicao(){
        return cbLivrosLocalDeEdicao;
    }
    public javax.swing.JComboBox<String> getCbEditora(){
        return cbLivroEditora;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bLivrosCadastrar;
    private javax.swing.JToggleButton bLivrosCancelar;
    private javax.swing.JToggleButton bLivrosConfirmarEdicao;
    private javax.swing.JToggleButton bLivrosEditar;
    private javax.swing.JComboBox<String> cbLivroEditora;
    private javax.swing.JComboBox<String> cbLivrosLocalDeEdicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtLivrosAutor;
    private javax.swing.JTextField txtLivrosISBN;
    private javax.swing.JTextField txtLivrosQuantidade;
    private javax.swing.JTextField txtLivrosTitulo;
    // End of variables declaration//GEN-END:variables
}
