/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.RevistaControl;
import controler.ValidacaoException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import vo.RevistaVO;

/**
 *
 * @author leonardo
 */
public class Revistas extends javax.swing.JFrame {

    /**
     * Creates new form Revistas
     */
    public Revistas() {
        initComponents();
    }
    private Principal buscaRevistaPrincipal; //tabela
    
    public Revistas(Principal buscaRevistaPrincipal) {
        initComponents();
        this.setTitle("Cadastro Revista");
        this.bRevistasConfirmarEdicao.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.buscaRevistaPrincipal = buscaRevistaPrincipal;
        this.bRevistasEditar.setEnabled(false);
        
    }
    
    public Revistas(Principal buscaRevistaPrincipal, RevistaVO revistaVO){
        initComponents();
        this.setTitle("Edição de Registro de Revista");
        this.bRevistasCadastrar.setEnabled(false);
        this.txtRevistaID.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.bRevistasConfirmarEdicao.setEnabled(false);
        this.buscaRevistaPrincipal = buscaRevistaPrincipal;
        
        this.txtRevistasQuantidade.setEnabled(false);
        this.txtRevistasTitulo.setEnabled(false);
        this.calendarRevistasData.setEnabled(false);
    
        popularCampos(revistaVO);
    }
    public void popularCampos(RevistaVO revistaVO){
        this.getTID().setText(String.valueOf(revistaVO.getId()));
        this.getTTitulo().setText(revistaVO.getTitulo());
        this.getTQuantidade().setText(String.valueOf(revistaVO.getQuantidade()));
        ((JTextField)calendarRevistasData.getDateEditor().getUiComponent()).setText(revistaVO.getData());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRevistasTitulo = new javax.swing.JTextField();
        calendarRevistasData = new com.toedter.calendar.JDateChooser();
        txtRevistasQuantidade = new javax.swing.JTextField();
        bRevistasEditar = new javax.swing.JToggleButton();
        bRevistasConfirmarEdicao = new javax.swing.JToggleButton();
        bRevistasCadastrar = new javax.swing.JToggleButton();
        bRevistasCancelar = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        txtRevistaID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel7.setText("*Todos os campos são obrigatórios.");

        jLabel1.setText("Titulo:");

        jLabel2.setText("Data Edição:");

        jLabel3.setText("Quantidade:");

        bRevistasEditar.setText("Editar");
        bRevistasEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRevistasEditarActionPerformed(evt);
            }
        });

        bRevistasConfirmarEdicao.setText("Confirmar Edição");
        bRevistasConfirmarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRevistasConfirmarEdicaoActionPerformed(evt);
            }
        });

        bRevistasCadastrar.setText("Cadastrar");
        bRevistasCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRevistasCadastrarActionPerformed(evt);
            }
        });

        bRevistasCancelar.setText("Cancelar");
        bRevistasCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRevistasCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRevistasTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(calendarRevistasData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtRevistasQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtRevistaID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(bRevistasEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bRevistasConfirmarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bRevistasCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bRevistasCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRevistaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRevistasTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calendarRevistasData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRevistasQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRevistasEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRevistasConfirmarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRevistasCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRevistasCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRevistasEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRevistasEditarActionPerformed
        this.txtRevistaID.setEnabled(false);
        this.txtRevistasTitulo.setEnabled(true);
        this.txtRevistasQuantidade.setEnabled(true);
        this.calendarRevistasData.setEnabled(true);
        this.bRevistasConfirmarEdicao.setEnabled(true);
        this.bRevistasEditar.setEnabled(false);
    }//GEN-LAST:event_bRevistasEditarActionPerformed

    private void bRevistasCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRevistasCadastrarActionPerformed
        try {
            
            RevistaControl revistaControl = new RevistaControl();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            String dataRevista = fmt.format(this.calendarRevistasData.getDate());
            revistaControl.cadastrar(this.txtRevistaID.getText(),this.txtRevistasTitulo.getText(), dataRevista, this.txtRevistasQuantidade.getText());
            this.buscaRevistaPrincipal.buscarRevistas();
            
            JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!", "Cadastro Revista", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
        } catch (ValidacaoException validacaoException) {
            
            JOptionPane.showMessageDialog(rootPane, validacaoException.getMessage(), "Cadastro Revista", JOptionPane.WARNING_MESSAGE);
        
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao efetuar o cadastro!", "Cadastro Revista", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_bRevistasCadastrarActionPerformed

    private void bRevistasCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRevistasCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bRevistasCancelarActionPerformed

    private void bRevistasConfirmarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRevistasConfirmarEdicaoActionPerformed
         try {
            RevistaControl revistaControl = new RevistaControl();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            String dataRevista = fmt.format(this.calendarRevistasData.getDate());
            revistaControl.editar(this.txtRevistaID.getText(),this.txtRevistasTitulo.getText(), dataRevista,this.txtRevistasQuantidade.getText());
            this.buscaRevistaPrincipal.buscarRevistas();
            
            
            JOptionPane.showMessageDialog(rootPane, "Edição realizada com sucesso!", "Editar Revista", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
        } catch (ValidacaoException validacaoException) {
            
            JOptionPane.showMessageDialog(rootPane, validacaoException.getMessage(), "Editar Revista", JOptionPane.WARNING_MESSAGE);
        
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao efetuar a edição!", "Editar Revista", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_bRevistasConfirmarEdicaoActionPerformed

    /**
     * @param args the command line arguments
     */
 
 public javax.swing.JTextField getTID(){
        return txtRevistaID;
    }
    public javax.swing.JTextField getTTitulo(){
        return txtRevistasTitulo;
    }
    public javax.swing.JTextField getTQuantidade(){
        return txtRevistasQuantidade;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bRevistasCadastrar;
    private javax.swing.JToggleButton bRevistasCancelar;
    private javax.swing.JToggleButton bRevistasConfirmarEdicao;
    private javax.swing.JToggleButton bRevistasEditar;
    private com.toedter.calendar.JDateChooser calendarRevistasData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtRevistaID;
    private javax.swing.JTextField txtRevistasQuantidade;
    private javax.swing.JTextField txtRevistasTitulo;
    // End of variables declaration//GEN-END:variables
}
